### ISSUE TITLE
[Feature Request] Batch generation with one prompt + random seed!

### ISSUE THREAD

**Issue by toyxyz** [neggles/animatediff-cli#12]
Thanks for the great work! Right now I have to run the generate every time I want to try a different seed from one prompt. It would be cool to be able to specify a number of videos that can be generated in sequence when a random seed[-1] is entered at one prompt! Like this Batch count = 10

**Comment by eremtsov** [comment]
Yes, I often find myself missing this. My workaround so far is just copy and paste the same prompt a bunch of times, but that's definitely less than ideal.

**Comment by neggles** [comment]
Yeah you can sort of do this already by just putting a single `-1` seed in the seed list, a single negative prompt in the negative list, and repeating the positive prompt, but it's not super great.

I can add a repeat argument that causes it to just loop through the provided prompts N times...

OK, done that in d4075c4 - run with `-r 4` and it'll repeat your prompt(s) 4 times, for example (goes through each one-by-one then does it again). Make sure all your seeds are on -1 (or you just have the one -1 seed) unless you want duplicates!

**Comment by toyxyz** [comment]
Works very well! Thank you!
![image](https://github.com/neggles/animatediff-cli/assets/8006000/0c6b426c-1371-4559-9dcb-0afda93ce688)
