### ISSUE TITLE
How to use rife?

### ISSUE THREAD

**Issue by howardgriffin** [neggles/animatediff-cli#13]
Hi, can you show me how to use rife in the Readme in detail? I don't know how to use it .

**Comment by Pythonpa** [comment]
Here's how I use it: 
`animatediff rife interpolate [your video frame sequence directory]   -c h264`
tips: Modify the contents of [ ] to specify the directory for your frame sequence, and without [ ],just directory.
and you can specify the output_dir,but I didn't use it.

**Comment by toyxyz** [comment]
Or you could also use Flowframe! https://nmkd.itch.io/flowframes

**Comment by neggles** [comment]
> Here's how I use it: `animatediff rife interpolate [your video frame sequence directory] -c h264` tips: Modify the contents of [ ] to specify the directory for your frame sequence, and without [ ],just directory. and you can specify the output_dir,but I didn't use it.

Bit late of a reply, but pretty much. I use this:

`animatediff rife interpolate -z -x -F 50 -M 3 /path/to/output/dir`
