### ISSUE TITLE
Did I use the embeddings correctly？

### ISSUE THREAD

**Issue by OoABYSSoO** [neggles/animatediff-cli#25]
![image](https://github.com/neggles/animatediff-cli/assets/125934639/92b36a5d-b576-48de-b612-a349a241038d)
Thank you for your project, it's very surprising,But I seem to have encountered a problem,It seems like I just loaded them, but I didn't use them. Is that the case? If so, how should I use them.

**Comment by neggles** [comment]
The log just lets you know that the files loaded successfully and are *available* to be used. If you put an embedding in the folder and it *doesn't* show up on that list, then something went wrong.

If you put one of the loaded embedding names (e.g. `bad_prompt_version2-neg`) into your prompt, or negative prompt, they'll be used 😄

**Comment by OoABYSSoO** [comment]
> 

Thank you for your reply
