### ISSUE TITLE
[Bug(?)] Using local checkpoint logic

### ISSUE THREAD

**Issue by LWprogramming** [neggles/animatediff-cli#30]
Should [this](https://github.com/neggles/animatediff-cli/blob/1911af251aba694b4fd0adc8458ca43fb4f46863/src/animatediff/utils/model.py#L37) instead check if the file exists? Is `model_index.json` meant to do anything otherwise?

**Comment by neggles** [comment]
That logic's detecting whether the HF model repo has been downloaded already or not, then downloads if it hasn't. The "base" model specifically has to already be in HF format.
