### ISSUE TITLE
What is the usage of the unform function in pipeline/context.py?

### ISSUE THREAD

**Issue by Z-YuPeng** [neggles/animatediff-cli#33]
Hi, thanks for your excellent work.
I have some trouble understanding the uniform function in pipeline/context.py. Why does this code introduce the bitwise operation?

**Comment by neggles** [comment]
Sorry for the slow reply! I honestly couldn't tell you. I copied it from the original animatediff code and despite my best efforts I've not been able to work out what it's doing or why 🤷‍♀️

**Comment by neggles** [comment]
Do let me know if you work it out, though 😅
