### ISSUE TITLE
The generated images and GIFs are pure black

### ISSUE THREAD

**Issue by ozmosis** [neggles/animatediff-cli#38]
`Using scheduler "k_dpmpp_2m_sde" (DPMSolverMultistepScheduler)                          generate.py:68
         INFO     Loading weights from E:\animatediff-cli\data\models\sd\majicmixRealistic_v7.safetensors generate.py:73
08:13:58 INFO     Merging weights into UNet...                                                            generate.py:90
08:13:59 INFO     Creating AnimationPipeline...                                                          generate.py:110
         INFO     No TI embeddings found                                                                 generate.py:131
         INFO     Sending pipeline to device "cuda"                                                       pipeline.py:22
         INFO     Selected data types: unet_dtype=torch.float16, tenc_dtype=torch.float16,                  device.py:90
                  vae_dtype=torch.float32
         INFO     Using channels_last memory format for UNet and VAE                                       device.py:109
08:14:02 INFO     Saving prompt config to output directory                                                    cli.py:290
         INFO     Initialization complete!                                                                    cli.py:299
         INFO     Generating 1 animations from 1 prompts                                                      cli.py:300
         INFO     Running generation 1 of 1 (prompt 1)                                                        cli.py:309
         INFO     Generation seed: 10925512164                                                                   cli.py:319
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20/20  [ 0:11:50 < 0:00:00 , ? it/s ]
08:26:00 INFO     Generation complete, saving...                                                         generate.py:175
         INFO     Saved sample to                                                                        generate.py:188
                  output\2024-03-18T08-13-43-girl-majicmixrealistic_v7\00_10925561214_1girl_solo_best-quali
                  ty_masterpiece_looking-at-viewer_purple-hair.gif
Saving frames to 00-10925564 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8  [ 0:00:00 < 0:00:00 , ? it/s ]
         INFO     Generation complete!                                                                        cli.py:345
         INFO     Done, exiting...` The generated images and GIFs are pure black

**Comment by jagan607** [comment]
Hi, were you able to solve this?

**Comment by neggles** [comment]
Usually all-black generations are the result of using a VAE that's not stable in fp16; try using this VAE `https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt` - you may need to merge it into the model you're using.

Alternatively you can run in fp32 but it'll be very slow
